spring.application.name=esiusuarios
#BASE DE DATOS (ACCESO SI USAMOS SPRING)
#spring.datasource.url = jdbc:mysql://172.20.48.23:3306/gramola?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&maxAllowedPacket=134217728
spring.datasource.url=jdbc:sqlserver://localhost:52016;databaseName=esiusuarios;encrypt=true;trustServerCertificate=true
spring.datasource.username = mariomg
spring.datasource.password = ces01mar05

# El dialecto para que Hibernate genere SQL optimizado para SQL Server
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect

# El driver oficial de Microsoft para SQL Server
spring.datasource.driver-class-name = com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

server.error.include-message=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8081